### ISSUE TITLE
Particular lines readonly

### ISSUE THREAD

**Issue by andrebnassis** [sachinraja/rodemirror#130]
Hello, 

First, congratulations for the amazing job. 

Is there any sample that shows how to set some lines as readonly, so it can't be edited? For example, lines 1,2 and 3 contains code that you cannot edit, but 4th and on it is possible to do it.

Thanks in advance!

**Comment by sachinraja** [comment]
Hey, the thanks is probably better given at https://github.com/codemirror/codemirror.next as this is just a very thin React wrapper over it. Your question is also better asked there as it is a question about the editor and not this React wrapper.

**Comment by andrebnassis** [comment]
I just released `codemirror-readonly-ranges` extension that easy allow to work with read-only ranges on CodeMirror6.
For anyone who is interested on the solution:

package: https://www.npmjs.com/package/codemirror-readonly-ranges

full documentation: https://andrebnassis.github.io/codemirror-readonly-ranges

**Comment by sachinraja** [comment]
Awesome, that looks really nice!
