### ISSUE TITLE
cursor move to position 0 on edition in controlled mode

### ISSUE THREAD

**Issue by iamdey** [sachinraja/rodemirror#20]
cf. https://codesandbox.io/s/quirky-booth-lgpom?file=/src/App.js

Moving the cursor by clicking or using arrow keys makes the changes added to the beginning of document.

https://user-images.githubusercontent.com/65737/126668480-731d970b-c699-4e8b-b89a-b103f060a04e.mp4

**Comment by sachinraja** [comment]
Yes, I am aware of this and opened an issue at codemirror/codemirror.next#533. I also noted this in the README:
> WARNING: Do not pass in a controlled value to the CodeMirror value prop. This will update the entire document on each update and will break the editor. If you want to update the value from a state, you can separate the reading and writing values.

**Comment by iamdey** [comment]
Woops I should RTFM better. Well reading the answer it seems that unfortunately a regular react paradigm will require a lot more work I suppose. 

Thanks for your answer.

**Comment by sachinraja** [comment]
It could be possible if you keep the selection in a state. I'll see if I can get something working soon.

**Comment by sachinraja** [comment]
I believe I've got this working [here](https://codesandbox.io/s/wizardly-elbakyan-rpojo?file=/src/App.js). Unsure as to whether I should support this or not because I'm sure performance is worse.

**Comment by sachinraja** [comment]
Hey, just letting you know, this should be working with the latest version now.
