### ISSUE TITLE
[Question] ho to get html when onUpdate

### ISSUE THREAD

**Issue by G11Max** [sachinraja/rodemirror#33]
Thanks for your great work. 

### Expect
```javascript
<div class="cm-line"><span class="ͼa">for</span> (<span class="ͼa">let</span> <span class="ͼf">a</span> = <span class="ͼc">0</span>; a &lt; bound; a++) <span class="cm-matchingBracket">{</span></div>
```
### Now
 > from view.state.doc.toString()

```
for (let a = 0; a < bound; a++) {
```

**Comment by sachinraja** [comment]
Hey, `view.state.doc.toString()` gets the text inputted in the editor. If you want the html you can use a [React `ref`](https://reactjs.org/docs/refs-and-the-dom.html) and pass it to the CodeMirror component. Access it's children with `ref.current.children`.
